name: backend
description: A new Dart Frog application
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=3.8.0 <4.0.0"

dependencies:
  crypto: ^3.0.7
  dart_frog: ^1.1.0
  dart_frog_auth: ^1.1.0
  equatable: ^2.0.7
  firedart: ^0.9.8
  http: ^1.6.0
  json_annotation: ^4.9.0
  meta: ^1.17.0
  postgres: ^3.5.9
  redis: ^4.0.0

dev_dependencies:
  build_runner: ^2.10.2       
  json_serializable: ^6.11.1  
  dart_frog_lint: ^0.1.0
  mocktail: ^1.0.3
  test: ^1.25.5